name: Build & Push Container Image

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  IMAGE_NAME: ${{ vars.APPLICATION_NAME }}
  CONTAINER_NAME: ${{ vars.APPLICATION_NAME }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      image_tag: ${{ steps.image-tag.outputs.tag }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY_HOSTNAME }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Restore counter from cache
        id: cache-restore
        uses: actions/cache@v4
        with:
          path: .github/build_counter
          # This key will almost never match exactly â€” but restore-keys finds the most recent
          key: build-counter-restore-${{ github.run_id }}
          restore-keys: |
            build-counter-

      - name: Generate image tag
        id: image-tag
        run: |
          mkdir -p .github
          DATE_TAG=$(date +'%Y%m%d')
          COUNTER_FILE=".github/build_counter"
          if [ -f "$COUNTER_FILE" ]; then
            LAST_DATE=$(cut -d' ' -f1 "$COUNTER_FILE")
            LAST_COUNT=$(cut -d' ' -f2 "$COUNTER_FILE")
            if [ "$LAST_DATE" = "$DATE_TAG" ]; then
              COUNT=$((LAST_COUNT + 1))
            else
              COUNT=1
            fi
          else
            COUNT=1
          fi
          echo "$DATE_TAG $COUNT" > "$COUNTER_FILE"
          TAG="${DATE_TAG}-${COUNT}"
          #echo "TAG=$TAG" >> $GITHUB_ENV
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "Image tag: $TAG"

      # - name: Container build and push
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: .
      #     file: Dockerfile
      #     push: true
      #     tags: ${{ vars.REGISTRY_HOSTNAME }}/dev/${{ env.IMAGE_NAME }}:${{ env.TAG }}

      - name: Output image tag using outputs
        run: |
          echo "Image tag output: ${{ steps.image-tag.outputs.tag }}"

      - name: Save counter to cache
        uses: actions/cache@v4
        with:
          path: .github/build_counter
          # Unique key for each build so it overwrites with new counter
          #key: build-counter-${{ env.TAG }}
          key: build-counter-${{ steps.image-tag.outputs.tag }}
