name: Build & Push Container Image

on:
  workflow_dispatch:
  # Uncomment the following lines to enable automatic builds on pushes to main branch
  # push:
  #   branches:
  #     - main

env:
  IMAGE_NAME: ${{ vars.APPLICATION_NAME }}
  CONTAINER_NAME: ${{ vars.APPLICATION_NAME }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      image_tag: ${{ steps.image-tag.outputs.tag }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY_HOSTNAME }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Generate image tag
        id: image-tag
        run: |
          mkdir -p .github
          TAG="$(date +%Y%m%d%H%M%S)"
          TAG_FILE=".github/build_tag"
          echo "$TAG" > "$TAG_FILE"
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "Image tag: $TAG"

      - name: Container build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ vars.REGISTRY_HOSTNAME }}/dev/${{ env.IMAGE_NAME }}:${{ steps.image-tag.outputs.tag }}

      - name: Save counter to cache
        uses: actions/cache@v4
        with:
          path: .github/build_tag
          # Unique key for each build so it overwrites with new tag
          key: build-tag-${{ steps.image-tag.outputs.tag }}

  # Uncomment the following lines to enable deployment after build
  # deploy:
  #   needs: build  # runs only after "build" completes
  #   uses: ./.github/workflows/container-deploy.yml
  #   with:
  #     tag: ${{ needs.build.outputs.image_tag }}
  #   secrets: inherit # pass all secrets
